#pragma once

/* Pokedex */

#define NO_MON		   0x00
#define MON_BULBASAUR  0x01
#define MON_IVYSAUR	   0x02
#define MON_VENUSAUR   0x03
#define MON_CHARMANDER 0x04
#define MON_CHARMELEON 0x05
#define MON_CHARIZARD  0x06
#define MON_SQUIRTLE   0x07
#define MON_WARTORTLE  0x08
#define MON_BLASTOISE  0x09
#define MON_CATERPIE   0x0A
#define MON_METAPOD	   0x0B
#define MON_BUTTERFREE 0x0C
#define MON_WEEDLE	   0x0D
#define MON_KAKUNA	   0x0E
#define MON_BEEDRILL   0x0F
#define MON_PIDGEY	   0x10
#define MON_PIDGEOTTO  0x11
#define MON_PIDGEOT	   0x12
#define MON_RATTATA	   0x13
#define MON_RATICATE   0x14
#define MON_SPEAROW	   0x15
#define MON_FEAROW	   0x16
#define MON_EKANS	   0x17
#define MON_ARBOK	   0x18
#define MON_PIKACHU	   0x19
#define MON_RAICHU	   0x1A
#define MON_SANDSHREW  0x1B
#define MON_SANDSLASH  0x1C
#define MON_NIDORAN_F  0x1D
#define MON_NIDORINA   0x1E
#define MON_NIDOQUEEN  0x1F
#define MON_NIDORAN_M  0x20
#define MON_NIDORINO   0x21
#define MON_NIDOKING   0x22
#define MON_CLEFAIRY   0x23
#define MON_CLEFABLE   0x24
#define MON_VULPIX	   0x25
#define MON_NINETALES  0x26
#define MON_JIGGLYPUFF 0x27
#define MON_WIGGLYTUFF 0x28
#define MON_ZUBAT	   0x29
#define MON_GOLBAT	   0x2A
#define MON_ODDISH	   0x2B
#define MON_GLOOM	   0x2C
#define MON_VILEPLUME  0x2D
#define MON_PARAS	   0x2E
#define MON_PARASECT   0x2F
#define MON_VENONAT	   0x30
#define MON_VENOMOTH   0x31
#define MON_DIGLETT	   0x32
#define MON_DUGTRIO	   0x33
#define MON_MEOWTH	   0x34
#define MON_PERSIAN	   0x35
#define MON_PSYDUCK	   0x36
#define MON_GOLDUCK	   0x37
#define MON_MANKEY	   0x38
#define MON_PRIMEAPE   0x39
#define MON_GROWLITHE  0x3A
#define MON_ARCANINE   0x3B
#define MON_POLIWAG	   0x3C
#define MON_POLIWHIRL  0x3D
#define MON_POLIWRATH  0x3E
#define MON_ABRA	   0x3F
#define MON_KADABRA	   0x40
#define MON_ALAKAZAM   0x41
#define MON_MACHOP	   0x42
#define MON_MACHOKE	   0x43
#define MON_MACHAMP	   0x44
#define MON_BELLSPROUT 0x45
#define MON_WEEPINBELL 0x46
#define MON_VICTREEBEL 0x47
#define MON_TENTACOOL  0x48
#define MON_TENTACRUEL 0x49
#define MON_GEODUDE	   0x4A
#define MON_GRAVELER   0x4B
#define MON_GOLEM	   0x4C
#define MON_PONYTA	   0x4D
#define MON_RAPIDASH   0x4E
#define MON_SLOWPOKE   0x4F
#define MON_SLOWBRO	   0x50
#define MON_MAGNEMITE  0x51
#define MON_MAGNETON   0x52
#define MON_FARFETCH   0x53
#define MON_DODUO	   0x54
#define MON_DODRIO	   0x55
#define MON_SEEL	   0x56
#define MON_DEWGONG	   0x57
#define MON_GRIMER	   0x58
#define MON_MUK		   0x59
#define MON_SHELLDER   0x5A
#define MON_CLOYSTER   0x5B
#define MON_GASTLY	   0x5C
#define MON_HAUNTER	   0x5D
#define MON_GENGAR	   0x5E
#define MON_ONIX	   0x5F
#define MON_DROWZEE	   0x60
#define MON_HYPNO	   0x61
#define MON_KRABBY	   0x62
#define MON_KINGLER	   0x63
#define MON_VOLTORB	   0x64
#define MON_ELECTRODE  0x65
#define MON_EXEGGCUTE  0x66
#define MON_EXEGGUTOR  0x67
#define MON_CUBONE	   0x68
#define MON_MAROWAK	   0x69
#define MON_HITMONLEE  0x6A
#define MON_HITMONCHAN 0x6B
#define MON_LICKITUNG  0x6C
#define MON_KOFFING	   0x6D
#define MON_WEEZING	   0x6E
#define MON_RHYHORN	   0x6F
#define MON_RHYDON	   0x70
#define MON_CHANSEY	   0x71
#define MON_TANGELA	   0x72
#define MON_KANGASKHAN 0x73
#define MON_HORSEA	   0x74
#define MON_SEADRA	   0x75
#define MON_GOLDEEN	   0x76
#define MON_SEAKING	   0x77
#define MON_STARYU	   0x78
#define MON_STARMIE	   0x79
#define MON_MR_MIME	   0x7A
#define MON_SCYTHER	   0x7B
#define MON_JYNX	   0x7C
#define MON_ELECTABUZZ 0x7D
#define MON_MAGMAR	   0x7E
#define MON_PINSIR	   0x7F
#define MON_TAUROS	   0x80
#define MON_MAGIKARP   0x81
#define MON_GYARADOS   0x82
#define MON_LAPRAS	   0x83
#define MON_DITTO	   0x84
#define MON_EEVEE	   0x85
#define MON_VAPOREON   0x86
#define MON_JOLTEON	   0x87
#define MON_FLAREON	   0x88
#define MON_PORYGON	   0x89
#define MON_OMANYTE	   0x8A
#define MON_OMASTAR	   0x8B
#define MON_KABUTO	   0x8C
#define MON_KABUTOPS   0x8D
#define MON_AERODACTYL 0x8E
#define MON_SNORLAX	   0x8F
#define MON_ARTICUNO   0x90
#define MON_ZAPDOS	   0x91
#define MON_MOLTRES	   0x92
#define MON_DRATINI	   0x93
#define MON_DRAGONAIR  0x94
#define MON_DRAGONITE  0x95
#define MON_MEWTWO	   0x96
#define MON_MEW		   0x97

/* Moves */

#define NO_MOVE			  0x00
#define MOVE_POUND		  0x01
#define MOVE_KARATE_CHOP  0x02
#define MOVE_DOUBLESLAP	  0x03
#define MOVE_COMET_PUNCH  0x04
#define MOVE_MEGA_PUNCH	  0x05
#define MOVE_PAY_DAY	  0x06
#define MOVE_FIRE_PUNCH	  0x07
#define MOVE_ICE_PUNCH	  0x08
#define MOVE_THUNDERPUNCH 0x09
#define MOVE_SCRATCH	  0x0A
#define MOVE_VICEGRIP	  0x0B
#define MOVE_GUILLOTINE	  0x0C
#define MOVE_RAZOR_WIND	  0x0D
#define MOVE_SWORDS_DANCE 0x0E
#define MOVE_CUT		  0x0F
#define MOVE_GUST		  0x10
#define MOVE_WING_ATTACK  0x11
#define MOVE_WHIRLWIND	  0x12
#define MOVE_FLY		  0x13
#define MOVE_BIND		  0x14
#define MOVE_SLAM		  0x15
#define MOVE_VINE_WHIP	  0x16
#define MOVE_STOMP		  0x17
#define MOVE_DOUBLE_KICK  0x18
#define MOVE_MEGA_KICK	  0x19
#define MOVE_JUMP_KICK	  0x1A
#define MOVE_ROLLING_KICK 0x1B
#define MOVE_SAND_ATTACK  0x1C
#define MOVE_HEADBUTT	  0x1D
#define MOVE_HORN_ATTACK  0x1E
#define MOVE_FURY_ATTACK  0x1F
#define MOVE_HORN_DRILL	  0x20
#define MOVE_TACKLE		  0x21
#define MOVE_BODY_SLAM	  0x22
#define MOVE_WRAP		  0x23
#define MOVE_TAKE_DOWN	  0x24
#define MOVE_THRASH		  0x25
#define MOVE_DOUBLE_EDGE  0x26
#define MOVE_TAIL_WHIP	  0x27
#define MOVE_POISON_STING 0x28
#define MOVE_TWINEEDLE	  0x29
#define MOVE_PIN_MISSILE  0x2A
#define MOVE_LEER		  0x2B
#define MOVE_BITE		  0x2C
#define MOVE_GROWL		  0x2D
#define MOVE_ROAR		  0x2E
#define MOVE_SING		  0x2F
#define MOVE_SUPERSONIC	  0x30
#define MOVE_SONICBOOM	  0x31
#define MOVE_DISABLE	  0x32
#define MOVE_ACID		  0x33
#define MOVE_EMBER		  0x34
#define MOVE_FLAMETHROWER 0x35
#define MOVE_MIST		  0x36
#define MOVE_WATER_GUN	  0x37
#define MOVE_HYDRO_PUMP	  0x38
#define MOVE_SURF		  0x39
#define MOVE_ICE_BEAM	  0x3A
#define MOVE_BLIZZARD	  0x3B
#define MOVE_PSYBEAM	  0x3C
#define MOVE_BUBBLEBEAM	  0x3D
#define MOVE_AURORA_BEAM  0x3E
#define MOVE_HYPER_BEAM	  0x3F
#define MOVE_PECK		  0x40
#define MOVE_DRILL_PECK	  0x41
#define MOVE_SUBMISSION	  0x42
#define MOVE_LOW_KICK	  0x43
#define MOVE_COUNTER	  0x44
#define MOVE_SEISMIC_TOSS 0x45
#define MOVE_STRENGTH	  0x46
#define MOVE_ABSORB		  0x47
#define MOVE_MEGA_DRAIN	  0x48
#define MOVE_LEECH_SEED	  0x49
#define MOVE_GROWTH		  0x4A
#define MOVE_RAZOR_LEAF	  0x4B
#define MOVE_SOLARBEAM	  0x4C
#define MOVE_POISONPOWDER 0x4D
#define MOVE_STUN_SPORE	  0x4E
#define MOVE_SLEEP_POWDER 0x4F
#define MOVE_PETAL_DANCE  0x50
#define MOVE_STRING_SHOT  0x51
#define MOVE_DRAGON_RAGE  0x52
#define MOVE_FIRE_SPIN	  0x53
#define MOVE_THUNDERSHOCK 0x54
#define MOVE_THUNDERBOLT  0x55
#define MOVE_THUNDER_WAVE 0x56
#define MOVE_THUNDER	  0x57
#define MOVE_ROCK_THROW	  0x58
#define MOVE_EARTHQUAKE	  0x59
#define MOVE_FISSURE	  0x5A
#define MOVE_DIG		  0x5B
#define MOVE_TOXIC		  0x5C
#define MOVE_CONFUSION	  0x5D
#define MOVE_PSYCHIC_M	  0x5E
#define MOVE_HYPNOSIS	  0x5F
#define MOVE_MEDITATE	  0x60
#define MOVE_AGILITY	  0x61
#define MOVE_QUICK_ATTACK 0x62
#define MOVE_RAGE		  0x63
#define MOVE_TELEPORT	  0x64
#define MOVE_NIGHT_SHADE  0x65
#define MOVE_MIMIC		  0x66
#define MOVE_SCREECH	  0x67
#define MOVE_DOUBLE_TEAM  0x68
#define MOVE_RECOVER	  0x69
#define MOVE_HARDEN		  0x6A
#define MOVE_MINIMIZE	  0x6B
#define MOVE_SMOKESCREEN  0x6C
#define MOVE_CONFUSE_RAY  0x6D
#define MOVE_WITHDRAW	  0x6E
#define MOVE_DEFENSE_CURL 0x6F
#define MOVE_BARRIER	  0x70
#define MOVE_LIGHT_SCREEN 0x71
#define MOVE_HAZE		  0x72
#define MOVE_REFLECT	  0x73
#define MOVE_FOCUS_ENERGY 0x74
#define MOVE_BIDE		  0x75
#define MOVE_METRONOME	  0x76
#define MOVE_MIRROR_MOVE  0x77
#define MOVE_SELFDESTRUCT 0x78
#define MOVE_EGG_BOMB	  0x79
#define MOVE_LICK		  0x7A
#define MOVE_SMOG		  0x7B
#define MOVE_SLUDGE		  0x7C
#define MOVE_BONE_CLUB	  0x7D
#define MOVE_FIRE_BLAST	  0x7E
#define MOVE_WATERFALL	  0x7F
#define MOVE_CLAMP		  0x80
#define MOVE_SWIFT		  0x81
#define MOVE_SKULL_BASH	  0x82
#define MOVE_SPIKE_CANNON 0x83
#define MOVE_CONSTRICT	  0x84
#define MOVE_AMNESIA	  0x85
#define MOVE_KINESIS	  0x86
#define MOVE_SOFTBOILED	  0x87
#define MOVE_HI_JUMP_KICK 0x88
#define MOVE_GLARE		  0x89
#define MOVE_DREAM_EATER  0x8A
#define MOVE_POISON_GAS	  0x8B
#define MOVE_BARRAGE	  0x8C
#define MOVE_LEECH_LIFE	  0x8D
#define MOVE_LOVELY_KISS  0x8E
#define MOVE_SKY_ATTACK	  0x8F
#define MOVE_TRANSFORM	  0x90
#define MOVE_BUBBLE		  0x91
#define MOVE_DIZZY_PUNCH  0x92
#define MOVE_SPORE		  0x93
#define MOVE_FLASH		  0x94
#define MOVE_PSYWAVE	  0x95
#define MOVE_SPLASH		  0x96
#define MOVE_ACID_ARMOR	  0x97
#define MOVE_CRABHAMMER	  0x98
#define MOVE_EXPLOSION	  0x99
#define MOVE_FURY_SWIPES  0x9A
#define MOVE_BONEMERANG	  0x9B
#define MOVE_REST		  0x9C
#define MOVE_ROCK_SLIDE	  0x9D
#define MOVE_HYPER_FANG	  0x9E
#define MOVE_SHARPEN	  0x9F
#define MOVE_CONVERSION	  0xA0
#define MOVE_TRI_ATTACK	  0xA1
#define MOVE_SUPER_FANG	  0xA2
#define MOVE_SLASH		  0xA3
#define MOVE_SUBSTITUTE	  0xA4
#define MOVE_STRUGGLE	  0xA5

/* Move Categories */

#define CAT_PHYSICAL 0x00
#define CAT_SPECIAL	 0x01
#define CAT_STATUS	 0x02

/* Pokemon/Move Types */

#define TYPE_NORMAL		  0x00
#define TYPE_FIGHTING	  0x01
#define TYPE_FLYING		  0x02
#define TYPE_POISON		  0x03
#define TYPE_GROUND		  0x04
#define TYPE_ROCK		  0x05
#define TYPE_BIRD		  0x06
#define TYPE_BUG		  0x07
#define TYPE_GHOST		  0x08
#define TYPE_FIRE		  0x14
#define TYPE_WATER		  0x15
#define TYPE_GRASS		  0x16
#define TYPE_ELECTRIC	  0x17
#define TYPE_PSYCHIC_TYPE 0x18
#define TYPE_ICE		  0x19
#define TYPE_DRAGON		  0x1A